#nullable disable

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BuilderGenerator at 2023-11-22T00:07:28 in 0.3907ms.
// </auto-generated>
//------------------------------------------------------------------------------
using System.CodeDom.Compiler;
using System;
using System.Collections.Generic;
using BuilderGenerator.IntegrationTests.Core.Models.Entities;

namespace BuilderGenerator.IntegrationTests.Net60.Builders
{
    public partial class UserBuilder : BuilderGenerator.Builder<BuilderGenerator.IntegrationTests.Core.Models.Entities.User>
    {
        public System.Lazy<System.DateTime> CreatedAt = new System.Lazy<System.DateTime>(() => default(System.DateTime));
        public System.Lazy<string> CreatedBy = new System.Lazy<string>(() => default(string));
        public System.Lazy<string> FirstName = new System.Lazy<string>(() => default(string));
        public System.Lazy<System.Guid> Id = new System.Lazy<System.Guid>(() => default(System.Guid));
        public System.Lazy<string> LastName = new System.Lazy<string>(() => default(string));
        public System.Lazy<string?> MiddleName = new System.Lazy<string?>(() => default(string?));
        public System.Lazy<System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>> Orders = new System.Lazy<System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>>(() => default(System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>));
        public System.Lazy<System.DateTime> UpdatedAt = new System.Lazy<System.DateTime>(() => default(System.DateTime));
        public System.Lazy<string> UpdatedBy = new System.Lazy<string>(() => default(string));

        public override BuilderGenerator.IntegrationTests.Core.Models.Entities.User Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new System.Lazy<BuilderGenerator.IntegrationTests.Core.Models.Entities.User>(() =>
                {
                    var result = new BuilderGenerator.IntegrationTests.Core.Models.Entities.User
                    {
                        CreatedAt = CreatedAt.Value,
                        CreatedBy = CreatedBy.Value,
                        FirstName = FirstName.Value,
                        Id = Id.Value,
                        LastName = LastName.Value,
                        MiddleName = MiddleName.Value,
                        Orders = Orders.Value,
                        UpdatedAt = UpdatedAt.Value,
                        UpdatedBy = UpdatedBy.Value,
                    };

                    return result;
                });

                PostProcess(Object.Value);
            }

            return Object.Value;
        }

        public UserBuilder WithCreatedAt(System.DateTime value)
        {
            return WithCreatedAt(() => value);
        }

        public UserBuilder WithCreatedAt(System.Func<System.DateTime> func)
        {
            CreatedAt = new System.Lazy<System.DateTime>(func);
            return this;
        }

        public UserBuilder WithoutCreatedAt()
        {
            CreatedAt = new System.Lazy<System.DateTime>(() => default(System.DateTime));
            return this;
        }

        public UserBuilder WithCreatedBy(string value)
        {
            return WithCreatedBy(() => value);
        }

        public UserBuilder WithCreatedBy(System.Func<string> func)
        {
            CreatedBy = new System.Lazy<string>(func);
            return this;
        }

        public UserBuilder WithoutCreatedBy()
        {
            CreatedBy = new System.Lazy<string>(() => default(string));
            return this;
        }

        public UserBuilder WithFirstName(string value)
        {
            return WithFirstName(() => value);
        }

        public UserBuilder WithFirstName(System.Func<string> func)
        {
            FirstName = new System.Lazy<string>(func);
            return this;
        }

        public UserBuilder WithoutFirstName()
        {
            FirstName = new System.Lazy<string>(() => default(string));
            return this;
        }

        public UserBuilder WithId(System.Guid value)
        {
            return WithId(() => value);
        }

        public UserBuilder WithId(System.Func<System.Guid> func)
        {
            Id = new System.Lazy<System.Guid>(func);
            return this;
        }

        public UserBuilder WithoutId()
        {
            Id = new System.Lazy<System.Guid>(() => default(System.Guid));
            return this;
        }

        public UserBuilder WithLastName(string value)
        {
            return WithLastName(() => value);
        }

        public UserBuilder WithLastName(System.Func<string> func)
        {
            LastName = new System.Lazy<string>(func);
            return this;
        }

        public UserBuilder WithoutLastName()
        {
            LastName = new System.Lazy<string>(() => default(string));
            return this;
        }

        public UserBuilder WithMiddleName(string? value)
        {
            return WithMiddleName(() => value);
        }

        public UserBuilder WithMiddleName(System.Func<string?> func)
        {
            MiddleName = new System.Lazy<string?>(func);
            return this;
        }

        public UserBuilder WithoutMiddleName()
        {
            MiddleName = new System.Lazy<string?>(() => default(string?));
            return this;
        }

        public UserBuilder WithOrders(System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order> value)
        {
            return WithOrders(() => value);
        }

        public UserBuilder WithOrders(System.Func<System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>> func)
        {
            Orders = new System.Lazy<System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>>(func);
            return this;
        }

        public UserBuilder WithoutOrders()
        {
            Orders = new System.Lazy<System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>>(() => default(System.Collections.Generic.ICollection<BuilderGenerator.IntegrationTests.Core.Models.Entities.Order>));
            return this;
        }

        public UserBuilder WithUpdatedAt(System.DateTime value)
        {
            return WithUpdatedAt(() => value);
        }

        public UserBuilder WithUpdatedAt(System.Func<System.DateTime> func)
        {
            UpdatedAt = new System.Lazy<System.DateTime>(func);
            return this;
        }

        public UserBuilder WithoutUpdatedAt()
        {
            UpdatedAt = new System.Lazy<System.DateTime>(() => default(System.DateTime));
            return this;
        }

        public UserBuilder WithUpdatedBy(string value)
        {
            return WithUpdatedBy(() => value);
        }

        public UserBuilder WithUpdatedBy(System.Func<string> func)
        {
            UpdatedBy = new System.Lazy<string>(func);
            return this;
        }

        public UserBuilder WithoutUpdatedBy()
        {
            UpdatedBy = new System.Lazy<string>(() => default(string));
            return this;
        }
    }
}
